# Generated by Django 5.0.7 on 2025-11-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_userprofile_achievements_userprofile_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievements_image',
            field=models.ImageField(blank=True, null=True, upload_to='leader_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certificates_image',
            field=models.ImageField(blank=True, null=True, upload_to='leader_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_image',
            field=models.ImageField(blank=True, null=True, upload_to='leader_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_image',
            field=models.ImageField(blank=True, null=True, upload_to='leader_docs/'),
        ),
    ]
